models:
  - name: fct_daily_platform_usage
    description: One row per company event on each date
    columns:
      - name: event_date
        description: the date each event takes place on. 
        data_tests:
          - not_null

      - name: company_id
        description: primary key for company id that is responsible for each event.
        data_tests:
          - not_null 
  
    